### PR TITLE
Replace player with mpvkt

### LINKED ISSUE #782: [▶️PL] Remember previous orientation of player
### Describe your suggested feature

This orientation option should work this way:
basically it should be in a fixed state (except landscape and reverse landscape that should adapt based on sensor, obviously).
Every time the user changes the orientation with this button on the player..
IMG_20221001_075856
the app should open other episodes of every anime with that orientation until the user presses the button again changing the default one.
Personally, the reason why i am asking this is that sometimes when i am tired on the bed i like to  watch anime in this position
IMG_20221001_080333
(image from the internet)
in this way watching an anine would be more comfortable. i am sure i am not the only who does this

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #1198: [▶️PL] Video gets Thin ratio in internal player after selecting "Stretched to screen" as default
### Steps to reproduce

Its simple.
1. After selecting "Stretched to screen" when I back out of the player and play something else
2. Then the video dimension gets thinner. (Images below for reference)
image

3. Also it goes away after selecting "Stretched to screen" again

### Expected behavior

The player should look like this in default after selecting "Stretched to screen"
image

Btw, it happens only when playing video at first after selecting fit to screen or anything else it goes back to normal ratio again. Also if "Fit to screen" is selected then it doesn't have this issue

### Actual behavior

The player just plays the video in that Thin ratio (image above for reference) after selecting any episode
So I noticed that after updating the app version to **Preview r6691** it started happening.

### Crash logs

_No response_

### Aniyomi version

Preview r6691

### Android version

Android 12

### Device

Samsung Galaxy M31

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/help/faq/) and [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #1279: [▶️PL] Hide progress bar when using double-tap to seek
### Describe your suggested feature

The progress bar should ideally not be visible when using double-tap to seek.

Many apps such as a MX Player, YouTube, VLC, have it hidden. Maybe have it be toggleable?

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #1352: Add more than 100% volume option
### Describe your suggested feature

There is a feature in VLC for extra volume by 100 percent. I like using internal player it is pretty good so could you add it in aniyomi player.

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #1583: Keyboard media buttons next/previous not working
### Steps to reproduce

Media button to play next and previous aren't working. I dont even have navigate chapters with media button turned on.
It's weird coz it works in pip mode.
I can click prev and next to change the video only in pip but not when I'm inside player

### Expected behavior

It should navigate between episodes in both cases - when inside player and - when in pip mode 

### Actual behavior

[Actual behavior Screen recording](https://github.com/aniyomiorg/aniyomi/assets/154865357/a57cc97a-c1e9-4e44-9b06-d4a6428c7a96)

### Crash logs

_No response_

### Aniyomi version

0.15.3.0-7543

### Android version

Android 14

### Device

OnePlus Pad

### Other details

App version: 0.15.3.0-7543 (standard, 224430ec0, 123, 2024-05-17T23:15Z)
Android version: 14 (SDK 34; build OPD2203_14.0.0.600(EX01))
Android build ID: OPD2203_14.0.0.600(EX01)
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OP59BCL1 (OPD2203)
Device model: OPD2203
WebView: Android System WebView 124.0.6367.123
MPV version: 4d32db2
Libplacebo version: v7.349.0
FFmpeg version: n7.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #1587: Remove useless mpv files in apk
### Steps to reproduce

image

For example, the files under the is.xyz.filepicker package should all be useless

### Expected behavior

These useless files should not be included.

### Actual behavior

A lot of useless mpv files are included in the apk

### Crash logs

_No response_

### Aniyomi version

0.15.3.0

### Android version

None

### Device

None

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #1750: Resuming after pausing in player causes the player freeze.
### Steps to reproduce

1. Open aniyomi. 
2. Open any anime from Library. 
3. Play an episode. 
4. Pause then resume. 

### Expected behavior

The player should start playing the episode normally. 

### Actual behavior

The player freezes completely not allowing to do anything and using the back button crashes the player and sends back episode list. 

### Crash logs

[aniyomi_crash_logs.txt](https://github.com/user-attachments/files/16628829/aniyomi_crash_logs.txt)

### Aniyomi version

0.16.4.3 (standard, 959f84a, 124, 2024-07-01T22:25Z)

### Android version

Android version: 14 (SDK 34; build lineage_cheeseburger-userdebug 14 AP2A.240705.005 0b7ea3f132) Android build ID: lineage_cheeseburger-userdebug 14 AP2A.240705.005 0b7ea3f132

### Device

 Device brand: OnePlus Device manufacturer: OnePlus Device name: OnePlus5 (OnePlus5) Device model: ONEPLUS A5000 WebView: Android System WebView 125.0.6422.165 MPV version: 4d32db2 Libplacebo version: v7.349.0 FFmpeg version: n7.0

### Other details

Temporarily using external player. Hoping get a fix soon. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #1767: Audio tracks missing from audio tab in local anime
### Steps to reproduce

1. Open an episode
2. Go to audio tab

### Expected behavior

It should list all audio tracks of said episode

### Actual behavior

There's no audio track, only "None"

### Crash logs

_No response_

### Aniyomi version

0.16.4.3-7809

### Android version

Android 10

### Device

Samsung Note 9

### Other details

There is audio playing, I just can't change the track because it doesn't show any.
In the subtitles tab all subtitle tracks are listed and it shows the correct one on the video, but it says "None" is selected.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #1801: Multiple subtitles at the same time
### Describe your suggested feature

Requesting ability to display multiple _embedded_  subtitles at the same time .
Would be great for people trying to learn a language, for example.

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is a request regarding an extension, I should be opening an issue in the extension's repository.
- [X] I have updated the app to version **[0.16.4.3](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Secozzi**
~`BaseMPVView.kt` and `KeyMapping.java` should probably be moved to mpvlib~

Closes #1801
Closes #1767
Closes #1750
Closes #1583 (probably)
Closes #1587
Closes #1352
Closes #1279
Closes #1198 (probably)
Closes #782

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/ui/player/AniyomiMPVView.kt
Comment (jmir1) [inline app/src/main/java/eu/kanade/tachiyomi/ui/player/AniyomiMPVView.kt:1]: Most of this is already implemented in the mpv library

File: app/src/main/java/eu/kanade/tachiyomi/ui/player/BaseMPVView.kt [hunk 1]
```diff
@@ -0,0 +1,115 @@
+package eu.kanade.tachiyomi.ui.player
+
+import android.content.Context
+import android.util.AttributeSet
+import android.util.Log
+import android.view.SurfaceHolder
+import android.view.SurfaceView
+import `is`.xyz.mpv.MPVLib
+
+// TODO: Maybe move to mpvlib?
```
Comment (jmir1) [inline app/src/main/java/eu/kanade/tachiyomi/ui/player/BaseMPVView.kt:10]: yeah I should do that.

File: app/src/main/java/eu/kanade/tachiyomi/ui/player/controls/components/DoubleTapSeekSecondsView.kt
Comment (jmir1) [inline app/src/main/java/eu/kanade/tachiyomi/ui/player/controls/components/DoubleTapSeekSecondsView.kt:1]: I'm putting a pin in this for myself, I want to change the double tap behaviour slightly.
Right now: 2 taps = 10 seconds, 3 taps = 10 seconds, 4 taps = 20 seconds etc.
I want it to be: 2 taps = 10 seconds, 3 taps = 20 seconds, 4 taps = 30 seconds etc.

File: app/src/main/java/mihon/core/migration/migrations/MigrateVideoOrientationMigration.kt
Comment (jmir1) [inline app/src/main/java/mihon/core/migration/migrations/MigrateVideoOrientationMigration.kt:1]: better name would be `VideoOrientationMigration`.

File: presentation-core/src/main/java/tachiyomi/presentation/core/components/material/Constants.kt [hunk 2]
```diff
@@ -17,10 +17,34 @@ class Padding {
...
     val small = 8.dp
 
     val extraSmall = 4.dp
 }
 
 val MaterialTheme.padding: Padding
     get() = Padding()
+
+// Used to make merging from mpvkt easier
+class MPVKtSpacing {
```
Comment (jmir1) [inline presentation-core/src/main/java/tachiyomi/presentation/core/components/material/Constants.kt:31]: We should probably just use the existing spacings

**Review by jmir1 — COMMENTED** [review]
I haven't finished reviewing this yet, just looked over the code a bit.

Also, we should put a license notice at the beginning of all the stolen bits of code from Abdallah. (Mostly the compose components I think)

Anyway, I have yet to run these changes in an emulator, I will review more when I get to that.

File: app/src/main/java/eu/kanade/tachiyomi/ui/player/AniyomiMPVView.kt
Comment (abdallahmehiz) [reply app/src/main/java/eu/kanade/tachiyomi/ui/player/AniyomiMPVView.kt:1]: It'd probably be better to use `BaseMPVView` instead of `MPVView`, no?
As Aniyomi's needs may differ from mpv-android's

File: app/src/main/java/eu/kanade/tachiyomi/ui/player/controls/components/panels/SubtitleSettingsTypographyCard.kt [hunk 3]
```diff
@@ -0,0 +1,343 @@
...
+        colors = panelCardsColors(),
+    ) {
+        Column {
+            var isBold by remember { mutableStateOf(MPVLib.getPropertyBoolean("sub-bold")) }
+            var isItalic by remember { mutableStateOf(MPVLib.getPropertyBoolean("sub-italic")) }
+            var justify by remember {
+                mutableStateOf(
+                    SubtitleJustification.entries.first {
+                        it.value == MPVLib.getPropertyString("sub-justify")
+                    },
```
Comment (jmir1) [inline app/src/main/java/eu/kanade/tachiyomi/ui/player/controls/components/panels/SubtitleSettingsTypographyCard.kt:138]: This crashes the app, not sure why

File: app/src/main/java/eu/kanade/tachiyomi/ui/player/BaseMPVView.kt (hunk 1 above)
Comment (jmir1) [reply app/src/main/java/eu/kanade/tachiyomi/ui/player/BaseMPVView.kt:10]: Done in 1.16.n

**Review by jmir1 — APPROVED** [review]

**Review by abdallahmehiz — APPROVED** [review]
Looks good to me aside from a few `TODO` comments here and there that should probably be removed.
