### PR TITLE
fix(tracking):don't show unusable tracking service

### LINKED ISSUE #1110: request for hiding unusable track system
### Describe your suggested feature

Since 'Baka manga updates' is not for anime or TV show tracks. So, it should not be shown in the 'Anime section'. Same goes for 'Simkl' in 'Manga section'.

### Other details

orca-image-1549835774

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by abdallahmehiz**
closes #1110

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/ui/entries/anime/track/AnimeTrackInfoDialog.kt [hunk 1]
```diff
@@ -249,7 +249,9 @@ data class AnimeTrackInfoDialogHomeScreen(
 
         private fun List<AnimeTrack>.mapToTrackItem(): List<AnimeTrackItem> {
             val dbTracks = map { it.toDbTrack() }
-            val loggedServices = Injekt.get<TrackManager>().services.filter { it.isLogged }
+            val loggedServices = Injekt.get<TrackManager>().services.filter {
+                it.isLogged && it.id != TrackManager.MANGA_UPDATES
```
Comment (jmir1) [inline app/src/main/java/eu/kanade/tachiyomi/ui/entries/anime/track/AnimeTrackInfoDialog.kt:253]:
```suggestion
                it.isLogged && it !is MangaTrackService
```

File: app/src/main/java/eu/kanade/tachiyomi/ui/entries/manga/track/MangaTrackInfoDialog.kt [hunk 2]
```diff
@@ -248,7 +248,9 @@ data class MangaTrackInfoDialogHomeScreen(
         }
 
         private fun List<MangaTrack>.mapToTrackItem(): List<MangaTrackItem> {
-            val loggedServices = Injekt.get<TrackManager>().services.filter { it.isLogged }
+            val loggedServices = Injekt.get<TrackManager>().services.filter {
+                it.isLogged && it.id != TrackManager.SIMKL
```
Comment (jmir1) [inline app/src/main/java/eu/kanade/tachiyomi/ui/entries/manga/track/MangaTrackInfoDialog.kt:252]:
```suggestion
                it.isLogged && it !is AnimeTrackService
```

File: app/src/main/java/eu/kanade/tachiyomi/ui/entries/anime/track/AnimeTrackInfoDialog.kt
Comment (jmir1) [inline app/src/main/java/eu/kanade/tachiyomi/ui/entries/anime/track/AnimeTrackInfoDialog.kt:1]: Of course you need to
```kotlin
import eu.kanade.tachiyomi.data.track.AnimeTrackService
import eu.kanade.tachiyomi.data.track.MangaTrackService
```

**Review by jmir1 — CHANGES_REQUESTED** [review]

**Review by jmir1 — APPROVED** [review]
